# Start with the official Node.js image
FROM node:22-alpine as builder

# Set the working directory
WORKDIR /app

# Copy package.json and package-lock.json before other files
# Utilise Docker cache to save re-installing dependencies if unchanged
COPY package.json package-lock.json* ./

# Install dependencies
RUN npm install

# Copy all files
COPY . .


# Build your application here, if you have a build step
# For example, for a React app: RUN npm run build

# Stage 2: Runtime
# Start from a clean, minimal image
FROM node:22-alpine

# Set the working directory
WORKDIR /app

# Only copy the built artifacts and necessary files from the builder stage
COPY --from=builder /app ./

# Build the Next.js app
RUN npm run build

# Expose the listening port
EXPOSE 80

# Run npm start to start the app
CMD ["npm", "start"]